    - name: change hostname
      shell: hostname $(hostname)-vpn
      
    - name: enabling epel repository (download)
      get_url: url=https://s3.amazonaws.com/amcaar/epel-release-6-8.noarch.rpm dest=/tmp/epel-release-6-8.noarch.rpm

    - name: enabling epel repository
      command: rpm -ivh /tmp/epel-release-6-8.noarch.rpm
      
    - name: update repositories cache and install openvpn package
      yum: name=openvpn enablerepo=epel state=latest

    - name: copy the client configuration file
      copy: src=/etc/openvpn/client.conf dest=/etc/openvpn/

    - name: copy the CA certificate
      copy: src=/tmp/ca.crt dest=/etc/openvpn/

    - name: copy the client certificate
      copy: src=/tmp/client.crt dest=/etc/openvpn/

    - name: copy the client key
      copy: src=/tmp/client.key dest=/etc/openvpn/

    - name: execute the vpn client
      command: openvpn --config client.conf --daemon --log openvpn_client.log  chdir=/etc/openvpn/ creates=/etc/openvpn/openvpn_client.log

